#!/bin/bash

export LANG=C
export LC_ALL=C

SCRIPTDIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

INFILE="$1"

if [ ! -s "$INFILE" ]
then
	echo >&2 "Error: input file '$INFILE' does not exist"
	exit 1
fi

INFILE="$(perl -MCwd=realpath -e 'print realpath($ARGV[0])' "$1")"

if [ ! -s "$INFILE" ]
then
	echo >&2 "Error: input file '$INFILE' does not exist"
	exit 1
fi

if [ -z "$CONDA_DEFAULT_ENV" ]
then
	source ${HOME}/miniconda3/bin/activate voromarmotte-env
fi

readonly TMPLDIR=$(mktemp -d)
trap "rm -r $TMPLDIR" EXIT

${SCRIPTDIR}/tools/calculate_vcblocks_and_run_trained_mlp_classifier.bash \
  "${SCRIPTDIR}/tools/trained_nn_models/training_5870c524a74c0e90c4e5a6ea40aac7bb/mlp_epoch_232.pt" \
  "$INFILE" \
> "${TMPLDIR}/table"

cd "$TMPLDIR"

R --vanilla << 'EOF' > /dev/null
df=read.table("table", header=TRUE, stringsAsFactors=FALSE);
area_total=sum(df$main_rr_contact__area);
area_expected_to_vanish=sum(df$main_rr_contact__area*(1-df$prediced_probability_to_persist));
area_expected_to_persist=sum(df$main_rr_contact__area*(0+df$prediced_probability_to_persist));
result=data.frame(area_total=area_total, area_expected_to_vanish=area_expected_to_vanish, area_expected_to_persist=area_expected_to_persist);
write.table(result, file="summary", row.names=FALSE, col.names=TRUE, quote=FALSE, sep="\t");
EOF

cat "${TMPLDIR}/summary"

