#!/bin/bash

function print_help_and_exit
{
cat >&2 << 'EOF'

'voromarmotte' predicts persistence of contact areas in a protein structure

Options:
    --input | -i              string  *  input file path or '_list' to read file paths from stdin
    --conda-path              string     conda installation path, default is ''
    --conda-env               string     conda environment name, default is 'voromarmotte-env'
    --subselect-contacts      string     query to subselect inter-chain contacts, default is '[]'
    --output-per-contact      string     output file path for the table of per-contact scores, default is ''
    --output-per-residue      string     output file path for the table of per-residue summary scores, default is ''
    --output-table-file       string     output file path for the global scores, default is '_stdout'
    --output-vscript          string     output file path for the visualization script for Voronota-GL
    --processors              number     maximum number of processors to run in parallel, default is 1
    --help | -h                          flag to display help message and exit

Standard output:
    space-separated table of global scores

Examples:

    ./voromarmotte  --input ./model.pdb --conda-path ~/miniconda3 --conda-env 'voromarmotte-env' > ./table.txt
    
    ./voromarmotte  --input ./model.pdb --subselect-contacts '[-inter-chain]' > ./table.txt
    
    ./voromarmotte  --input ./model.pdb --output-per-contact ./table_of_contacts.txt > ./table.txt
    
    find ./models/ -type f -name '*.pdb' | ./voromarmotte --input _list --subselect-contacts '[-inter-chain]' > ./table.txt

EOF
exit 1
}

################################################################################

export LANG=C
export LC_ALL=C

SCRIPTDIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

readonly ZEROARG=$0
ALLARGS=("$@")

INFILE=""
CONDA_PATH=""
CONDA_ENV="voromarmotte-env"
SUBSELECT_CONTACTS="[]"
OUTPUT_PER_CONTACT=""
OUTPUT_PER_RESIDUE=""
OUTPUT_VSCRIPT=""
MAX_PROCESSORS="1"
HELP_MODE="false"

while [[ $# > 0 ]]
do
	OPTION="$1"
	OPTARG="$2"
	shift
	case $OPTION in
	-i|--input)
		INFILE="$OPTARG"
		shift
		;;
	--conda-path)
		CONDA_PATH="$OPTARG"
		shift
		;;
	--conda-env)
		CONDA_ENV="$OPTARG"
		shift
		;;
	--subselect-contacts)
		SUBSELECT_CONTACTS="$OPTARG"
		shift
		;;
	--output-per-contact)
		OUTPUT_PER_CONTACT="$OPTARG"
		shift
		;;
	--output-per-residue)
		OUTPUT_PER_RESIDUE="$OPTARG"
		shift
		;;
	--output-vscript)
		OUTPUT_VSCRIPT="$OPTARG"
		shift
		;;
	--output-table-file)
		OUTPUT_TABLE_FILE="$OPTARG"
		shift
		;;
	--processors)
		MAX_PROCESSORS="$OPTARG"
		shift
		;;
	-h|--help)
		HELP_MODE="true"
		;;
	*)
		echo >&2 "Error: invalid command line option '$OPTION'"
		exit 1
		;;
	esac
done

if [ "$HELP_MODE" == "true" ]
then
	print_help_and_exit
fi

################################################################################

if [ -z "$INFILE" ]
then
	echo >&2 "Error: no input provided"
	exit 1
fi

if [ "$INFILE" != "_list" ] && [ ! -s "$INFILE" ]
then
	echo >&2 "Error: input file '$INFILE' does not exist"
	exit 1
fi

################################################################################

if [ -z "$CONDA_DEFAULT_ENV" ]
then
	if [ -z "$CONDA_PATH" ]
	then
		echo >&2 "Error: not in conda environment, and the conda path is not provided"
		exit 1
	fi
	
	if [ ! -s "${CONDA_PATH}/bin/activate" ]
	then
		echo >&2 "Error: no conda activation script '${CONDA_PATH}/bin/activate'"
		exit 1
	fi
	
	source "${CONDA_PATH}/bin/activate"
fi

if [ -n "$CONDA_ENV" ]
then
	if [ "$CONDA_DEFAULT_ENV" != "$CONDA_ENV" ]
	then
		conda activate "$CONDA_ENV"
	fi
	
	if [ "$CONDA_DEFAULT_ENV" != "$CONDA_ENV" ]
	then
		echo >&2 "Error: no '$CONDA_ENV' environment"
		exit 1
	fi
fi

command -v R &> /dev/null || { echo >&2 "Error: 'R' executable not in binaries path"; exit 1; }

################################################################################

if [ "$INFILE" == "_list" ]
then
	readonly TMPLDIR=$(mktemp -d)
	trap "rm -r $TMPLDIR" EXIT
	
	cat | egrep . | sort | uniq > "$TMPLDIR/input_list"
	
	if [ ! -s "$TMPLDIR/input_list" ]
	then
		echo >&2 "Error: no stdin data"
		exit 1
	fi
	
	mkdir -p "$TMPLDIR/children_tables"
	
	cat "$TMPLDIR/input_list" \
	| awk -v outdir="$TMPLDIR/children_tables" '{print "--input " $1 " --output-table-file " outdir "/" NR ".pdb"}' \
	| xargs -L 1 -P "$MAX_PROCESSORS" "$ZEROARG" "${ALLARGS[@]}"
	
	find "$TMPLDIR/children_tables" -type f -not -empty \
	| sort \
	| xargs -L 1 cat \
	| awk '{if(NR==1 || $1!="ID") print $0}' \
	| ${SCRIPTDIR}/tools/voronota-js --no-setup-defaults "js:voronota_tournament_sort('-input-file _stdin -output-file _stdout -columns area_pseudoenergy -multipliers -1 -tolerances 0.0');" \
	| column -t \
	> "$TMPLDIR/full_output_table"
	
	if [ -n "$OUTPUT_TABLE_FILE" ] && [ "$OUTPUT_TABLE_FILE" != "_stdout" ]
	then
		mkdir -p "$(dirname "$OUTPUT_TABLE_FILE")"
		cat "$TMPLDIR/full_output_table" > "$OUTPUT_TABLE_FILE"
	else
		cat "$TMPLDIR/full_output_table"
	fi
	
	exit 0
fi

################################################################################

INFILE="$(perl -MCwd=realpath -e 'print realpath($ARGV[0])' "$INFILE")"

if [ ! -s "$INFILE" ]
then
	echo >&2 "Error: input file '$INFILE' does not exist"
	exit 1
fi

readonly TMPLDIR=$(mktemp -d)
trap "rm -r $TMPLDIR" EXIT

${SCRIPTDIR}/tools/calculate_vcblocks_and_run_trained_mlp_classifier.bash \
  "${SCRIPTDIR}/tools/trained_nn_models/training_5870c524a74c0e90c4e5a6ea40aac7bb/mlp_epoch_232.pt" \
  "$INFILE" \
  "$SUBSELECT_CONTACTS" \
> "${TMPLDIR}/table"

if [ ! -s "${TMPLDIR}/table" ]
then
	echo >&2 "Error: failed to generate predictions"
	exit 1
fi

cd "$TMPLDIR"

R --vanilla << 'EOF' > /dev/null
df=read.table("table", header=TRUE, stringsAsFactors=FALSE);
total_area=sum(df$main_rr_contact__area);
df$area_expected_to_vanish=(df$main_rr_contact__area*(1-df$predicted_probability_to_persist));
df$area_expected_to_persist=(df$main_rr_contact__area*(0+df$predicted_probability_to_persist));
df$bounded_probabilities=df$predicted_probability_to_persist;
df$bounded_probabilities[which(df$predicted_probability_to_persist<0.005)]=0.005;
df$bounded_probabilities[which(df$predicted_probability_to_persist>0.995)]=0.995;
df$area_badness=0-(df$main_rr_contact__area*log(df$bounded_probabilities));
df$area_goodness=0-(df$main_rr_contact__area*log(1.0-df$bounded_probabilities));
df$area_pseudoenergy=0-(df$area_goodness-df$area_badness);
total_area=sum(df$main_rr_contact__area);
total_area_expected_to_vanish=sum(df$area_expected_to_vanish);
total_area_expected_to_persist=sum(df$area_expected_to_persist);
total_area_pseudoenergy=sum(df$area_pseudoenergy);
total_area_badness=sum(df$area_badness);
total_area_goodness=sum(df$area_goodness);
df$exposure_value=(df$main_rr_contact__boundary)/sqrt(df$main_rr_contact__area);
ordering_by_exposure_value=order(0-df$exposure_value);
ordered_exposure_values=df$exposure_value[ordering_by_exposure_value];
ordered_area_pseudoenergies=df$area_pseudoenergy[ordering_by_exposure_value];
ordered_areas=df$main_rr_contact__area[ordering_by_exposure_value];
N=length(ordered_exposure_values);
M=max(1, length(which(ordered_exposure_values>0)));
subtotal_area_pseudoenergies=rep(0, M);
subtotal_areas=rep(0, M);
for(i in 1:M)
{
	subtotal_area_pseudoenergies[i]=sum(ordered_area_pseudoenergies[i:N]);
	subtotal_areas[i]=sum(ordered_areas[i:N]);
}
best_core_index=order(subtotal_area_pseudoenergies)[1];
best_core_area_pseudoenergy=subtotal_area_pseudoenergies[best_core_index];
best_core_area=subtotal_areas[best_core_index];
result=data.frame(ID="IDVALUE", area_pseudoenergy=total_area_pseudoenergy, area_total=total_area, area_expected_to_persist=total_area_expected_to_persist, area_expected_to_vanish=total_area_expected_to_vanish, area_goodness=total_area_goodness, area_badness=total_area_badness, best_core_pseudoenergy=best_core_area_pseudoenergy, best_core_area=best_core_area);
write.table(result, file="summary", row.names=FALSE, col.names=TRUE, quote=FALSE, sep="\t");
EOF

if [ -n "$OUTPUT_PER_RESIDUE" ]
then
R --vanilla << 'EOF' > /dev/null
df=read.table("table", header=TRUE, stringsAsFactors=FALSE);
df$area_expected_to_persist=df$main_rr_contact__area*df$predicted_probability_to_persist;
df$area_expected_to_vanish=df$main_rr_contact__area*(1-df$predicted_probability_to_persist);
sdf1=df[,c("area_expected_to_persist", "area_expected_to_vanish")];
sdf2=sdf1;
sdf1$chain=df$chain1;
sdf1$seqnum=df$seqnum1;
sdf1$resname=df$resname1;
sdf2$chain=df$chain2;
sdf2$seqnum=df$seqnum2;
sdf2$resname=df$resname2;
sdf=rbind(sdf1, sdf2);
sdf_summarized=aggregate(. ~ chain + seqnum + resname, data=sdf, FUN=sum);
sdf_summarized=sdf_summarized[order(0-sdf_summarized$area_expected_to_vanish),];
write.table(sdf_summarized, file="table_per_residue", row.names=FALSE, col.names=TRUE, quote=FALSE, sep="\t");
EOF
fi

cd - &> /dev/null

if [ ! -s "${TMPLDIR}/summary" ]
then
	echo >&2 "Error: failed to global summary"
	exit 1
fi

if [ -n "$OUTPUT_PER_CONTACT" ]
then
	mkdir -p "$(dirname ${OUTPUT_PER_CONTACT})"
	cat "${TMPLDIR}/table" > "$OUTPUT_PER_CONTACT"
fi

if [ -n "$OUTPUT_PER_RESIDUE" ]
then
	mkdir -p "$(dirname ${OUTPUT_PER_RESIDUE})"
	cat "${TMPLDIR}/table_per_residue" > "$OUTPUT_PER_RESIDUE"
fi

if [ -n "$OUTPUT_VSCRIPT" ]
then
	mkdir -p "$(dirname ${OUTPUT_VSCRIPT})"
	
	{
		echo 'color-atoms -col yellow'
		echo 'construct-contacts-radically-fast -no-intra-residue -generate-graphics'
		cat "${TMPLDIR}/table" | tail -n +2 | awk '{print "set-adjunct-of-contacts -use [-a1 [-chain " $2 " -rnum " $3 "] -a2 [-chain " $5 " -rnum " $6 "]] -name persistence -value " $10}'
		echo "show-contacts ((${SUBSELECT_CONTACTS}) and ([-v persistence]))"
		echo 'spectrum-contacts -use [_visible] -adjunct persistence -scheme rwb -min-val 0.0 -max-val 1.0'
	} > "$OUTPUT_VSCRIPT"
fi

cat "${TMPLDIR}/summary" \
| sed "s|IDVALUE|$(basename ${INFILE})|" \
| column -t \
| {
if [ -n "$OUTPUT_TABLE_FILE" ] && [ "$OUTPUT_TABLE_FILE" != "_stdout" ]
then
	mkdir -p "$(dirname ${OUTPUT_TABLE_FILE})"
	cat > "$OUTPUT_TABLE_FILE"
else
	cat
fi
}


