#!/bin/bash

function print_help_and_exit
{
cat >&2 << 'EOF'

'voromarmotte' predicts persistence of contact areas in a protein structure

Options:
    --input | -i              string  *  input file path or '_list' to read file paths from stdin
    --conda-path              string     conda installation path, default is '${HOME}/miniconda3'
    --conda-env               string     conda environment name, default is 'voromarmotte-env'
    --rebuild-sidechains      string     flag to rebuild side-chains with FASPR, can be 'false' or 'true', default is 'false'
    --mutate-sidechains       string     triples of strings (chain resnum resname) to define mutations and rebuild with FASPR
    --relax-with-openmm       string     parameters (':'-separated tokens, or 'basic') to enable the OpenMM relaxation, default is ''
    --subselect-contacts      string     query to subselect inter-chain contacts, default is '[]'
    --output-atoms-file       string     output file path for the processed input atoms
    --output-per-contact      string     output file path for the table of per-contact scores, default is ''
    --output-per-residue      string     output file path for the table of per-residue summary scores, default is ''
    --output-table-file       string     output file path for the global scores, default is '_stdout'
    --output-vscript          string     output file path for the visualization script for Voronota-GL
    --output-pymol-vscript    string     output file path for the visualization script for PyMol
    --processors              number     maximum number of processors to run in parallel, default is 1
    --help | -h                          flag to display help message and exit

Standard output:
    space-separated table of global scores

Examples:

    ./voromarmotte  --input ./model.pdb --conda-path ~/miniconda3 --conda-env 'voromarmotte-env' > ./table.txt
    
    ./voromarmotte  --input ./model.pdb --subselect-contacts '[-inter-chain]' > ./table.txt
    
    ./voromarmotte  --input ./model.pdb --output-per-contact ./table_of_contacts.txt > ./table.txt
    
    find ./models/ -type f -name '*.pdb' | ./voromarmotte --input _list --subselect-contacts '[-inter-chain]' > ./table.txt

EOF
exit 1
}

function substitute_in_string
{
	SUBSTITUTE_TEMPLATE="$1"
	SUBSTITUTE_SOURCE="$2"
	SUBSTITUTE_DESTINATION="$3"
	SUBSTITUTE_DESTINATION="$(basename ${SUBSTITUTE_DESTINATION} .pdb)"
	SUBSTITUTE_DESTINATION="$(basename ${SUBSTITUTE_DESTINATION} .cif)"
	echo "$SUBSTITUTE_TEMPLATE" | sed "s|${SUBSTITUTE_SOURCE}|${SUBSTITUTE_DESTINATION}|"
}

################################################################################

export LANG=C
export LC_ALL=C

SCRIPTDIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

readonly ZEROARG=$0
ALLARGS=("$@")

INFILE=""
CONDA_PATH="${HOME}/miniconda3"
CONDA_ENV="voromarmotte-env"
REBUILD_SIDECHAINS="false"
MUTATE_SIDECHAINS=""
RELAX_WITH_OPENMM=""
SUBSELECT_CONTACTS="[]"
OUTPUT_ATOMS_FILE=""
OUTPUT_PER_CONTACT=""
OUTPUT_PER_RESIDUE=""
OUTPUT_TABLE_FILE=""
OUTPUT_VSCRIPT=""
OUTPUT_PYMOL_VSCRIPT=""
MAX_PROCESSORS="1"
HELP_MODE="false"

while [[ $# > 0 ]]
do
	OPTION="$1"
	OPTARG="$2"
	shift
	case $OPTION in
	-i|--input)
		INFILE="$OPTARG"
		shift
		;;
	--conda-path)
		CONDA_PATH="$OPTARG"
		shift
		;;
	--conda-env)
		CONDA_ENV="$OPTARG"
		shift
		;;
	--rebuild-sidechains)
		REBUILD_SIDECHAINS="$OPTARG"
		shift
		;;
	--mutate-sidechains)
		MUTATE_SIDECHAINS="$OPTARG"
		shift
		;;
	--relax-with-openmm)
		RELAX_WITH_OPENMM="$OPTARG"
		shift
		;;
	--subselect-contacts)
		SUBSELECT_CONTACTS="$OPTARG"
		shift
		;;
	--output-atoms-file)
		OUTPUT_ATOMS_FILE="$OPTARG"
		shift
		;;
	--output-per-contact)
		OUTPUT_PER_CONTACT="$OPTARG"
		shift
		;;
	--output-per-residue)
		OUTPUT_PER_RESIDUE="$OPTARG"
		shift
		;;
	--output-vscript)
		OUTPUT_VSCRIPT="$OPTARG"
		shift
		;;
	--output-pymol-vscript)
		OUTPUT_PYMOL_VSCRIPT="$OPTARG"
		shift
		;;
	--output-table-file)
		OUTPUT_TABLE_FILE="$OPTARG"
		shift
		;;
	--processors)
		MAX_PROCESSORS="$OPTARG"
		shift
		;;
	-h|--help)
		HELP_MODE="true"
		;;
	*)
		echo >&2 "Error: invalid command line option '$OPTION'"
		exit 1
		;;
	esac
done

if [ "$HELP_MODE" == "true" ]
then
	print_help_and_exit
fi

################################################################################

if [ -z "$INFILE" ]
then
	echo >&2 "Error: no input provided"
	exit 1
fi

if [ "$INFILE" != "_list" ] && [ ! -s "$INFILE" ]
then
	echo >&2 "Error: input file '$INFILE' does not exist"
	exit 1
fi

################################################################################

if [ "$REBUILD_SIDECHAINS" != "false" ] && [ "$REBUILD_SIDECHAINS" != "true" ]
then
	echo >&2 "Error: invalid value '${REBUILD_SIDECHAINS}' for the side-chain rebuilding flag, must be 'false' or 'true'"
	exit 1
fi

################################################################################

if [ -z "$CONDA_DEFAULT_ENV" ]
then
	if [ -z "$CONDA_PATH" ]
	then
		echo >&2 "Error: not in conda environment, and the conda path is not provided"
		exit 1
	fi
	
	if [ ! -s "${CONDA_PATH}/bin/activate" ]
	then
		echo >&2 "Error: no conda activation script '${CONDA_PATH}/bin/activate'"
		exit 1
	fi
	
	source "${CONDA_PATH}/bin/activate"
fi

if [ -n "$CONDA_ENV" ]
then
	if [ "$CONDA_DEFAULT_ENV" != "$CONDA_ENV" ]
	then
		conda activate "$CONDA_ENV"
	fi
	
	if [ "$CONDA_DEFAULT_ENV" != "$CONDA_ENV" ]
	then
		echo >&2 "Error: no '$CONDA_ENV' environment"
		exit 1
	fi
fi

command -v R &> /dev/null || { echo >&2 "Error: 'R' executable not in binaries path"; exit 1; }

readonly TMPLDIR=$(mktemp -d)
trap "rm -r $TMPLDIR" EXIT

################################################################################

if [ "$INFILE" == "_list" ]
then
	cat | egrep . | sort | uniq > "$TMPLDIR/input_list"
	
	if [ ! -s "$TMPLDIR/input_list" ]
	then
		echo >&2 "Error: no stdin data"
		exit 1
	fi
	
	mkdir -p "$TMPLDIR/children_tables"
	
	cat "$TMPLDIR/input_list" \
	| {
	if [ "$MUTATE_SIDECHAINS" == "_list" ]
	then
		cat \
		| sed 's/^\s*\(\S\+\)\s\+\(.*\)$/\1_FIRSTGAP_\2/' | tr ' ' '_' | tr '\t' '_' | sed 's/_FIRSTGAP_/ /' \
		| awk -v outdir="$TMPLDIR/children_tables" '{print "--input " $1 " --mutate-sidechains " $2 " --output-table-file " outdir "/" NR ".pdb"}'
	else
		awk -v outdir="$TMPLDIR/children_tables" '{print "--input " $1 " --output-table-file " outdir "/" NR ".pdb"}'
	fi
	} \
	| xargs -L 1 -P "$MAX_PROCESSORS" "$ZEROARG" "${ALLARGS[@]}" --processors 1
	
	find "$TMPLDIR/children_tables" -type f -not -empty \
	| sort \
	| xargs -L 1 cat \
	| awk '{if(NR==1 || $1!="ID") print $0}' \
	| ${SCRIPTDIR}/tools/voronota-js --no-setup-defaults "js:voronota_tournament_sort('-input-file _stdin -output-file _stdout -columns area_pseudoenergy -multipliers -1 -tolerances 0.0');" \
	| column -t \
	> "$TMPLDIR/full_output_table"
	
	if [ -n "$OUTPUT_TABLE_FILE" ] && [ "$OUTPUT_TABLE_FILE" != "_stdout" ]
	then
		mkdir -p "$(dirname "$OUTPUT_TABLE_FILE")"
		cat "$TMPLDIR/full_output_table" > "$OUTPUT_TABLE_FILE"
	else
		cat "$TMPLDIR/full_output_table"
	fi
	
	exit 0
fi

################################################################################

INFILE="$(perl -MCwd=realpath -e 'print realpath($ARGV[0])' "$INFILE")"

if [ ! -s "$INFILE" ]
then
	echo >&2 "Error: input file '$INFILE' does not exist"
	exit 1
fi

if [ -n "$MUTATE_SIDECHAINS" ]
then
	if [[ "$MUTATE_SIDECHAINS" == "interface"* ]]
	then
		read MUTATE_CHAIN MUTATE_TO_RNAME <<< "$(echo ${MUTATE_SIDECHAINS} | tr '-' ' ' | tr '_' ' ' | tr '=' ' ' | tr ':' ' ' | awk '{print $2 " " $3}')"
		{
			${SCRIPTDIR}/tools/voronota-lt \
			  --input "$INFILE" \
			  --compute-only-inter-chain-contacts \
			  --print-contacts-residue-level \
			2> /dev/null
		} \
		| awk '{if($1=="cr"){print $2 " " $3 "\n" $5 " " $6}}' | tr '|' ' ' | sort | uniq \
		| awk -v chainsel=${MUTATE_CHAIN} '{if($1==chainsel){print $2 " " $3}}' \
		| while read -r LINERNUM LINERNAME
		do
			if [ "$MUTATE_TO_RNAME" == "every" ]
			then
				for IRNAME in ALA ARG ASN ASP CYS GLN GLU GLY HIS ILE LEU LYS MET PHE PRO SER THR TRP TYR VAL
				do
					if [ "$IRNAME" != "$LINERNAME" ]
					then
						echo "${INFILE} ${MUTATE_CHAIN} ${LINERNUM} ${IRNAME}"
					fi
				done
			else
				if [ "$MUTATE_TO_RNAME" != "$LINERNAME" ]
				then
					echo "${INFILE} ${MUTATE_CHAIN} ${LINERNUM} ${MUTATE_TO_RNAME}"
				fi
			fi
		done \
		> "$TMPLDIR/input_mutations_list"
		
		if [ ! -s "$TMPLDIR/input_mutations_list" ]
		then
			echo >&2 "Error: failed to generated interface mutation requests"
			exit 1
		fi
		
		{
			cat "$TMPLDIR/input_mutations_list"
			echo "${INFILE} any any original"
		} \
		| "$ZEROARG" "${ALLARGS[@]}" --input _list --mutate-sidechains _list
		
		exit 0
	fi
	
	if [[ "$MUTATE_SIDECHAINS" == *"every"* ]]
	then
		${SCRIPTDIR}/tools/voronota-lt \
		  --input "$INFILE" \
		  --write-input-balls-to-file "$TMPLDIR/all_input_atomic_balls" \
		  --exit-before-calculations \
		2> /dev/null

		for IRNAME in ALA ARG ASN ASP CYS GLN GLU GLY HIS ILE LEU LYS MET PHE PRO SER THR TRP TYR VAL
		do
			echo "$(echo "${MUTATE_SIDECHAINS}" | sed "s/every/${IRNAME}/g")"
		done \
		| tr ' ' '_' \
		| sort | uniq \
		> "$TMPLDIR/mutations_list_all"
		
		cat "$TMPLDIR/all_input_atomic_balls" \
		| awk '{print $1 "_" $2}' \
		| tr '|' '_' \
		| sort | uniq \
		> "$TMPLDIR/mutations_list_forbidden"
		
		{
			cat "$TMPLDIR/mutations_list_all"
			cat "$TMPLDIR/mutations_list_forbidden"
			cat "$TMPLDIR/mutations_list_forbidden"
		} \
		| sort | uniq -c \
		| awk '{if($1==1){print $2}}' \
		| tr '_' ' ' \
		| sed "s|^|${INFILE} |" \
		> "$TMPLDIR/input_mutations_list"
		
		if [ ! -s "$TMPLDIR/input_mutations_list" ]
		then
			echo >&2 "Error: failed to generated mutation requests"
			exit 1
		fi
		
		{
			cat "$TMPLDIR/input_mutations_list"
			echo "${INFILE} any any original"
		} \
		| "$ZEROARG" "${ALLARGS[@]}" --input _list --mutate-sidechains _list
		
		exit 0
	fi
fi

if [ "$REBUILD_SIDECHAINS" == "true" ] || [ -n "$MUTATE_SIDECHAINS" ]
then
	MUTATE_SIDECHAINS="$(echo ${MUTATE_SIDECHAINS} | tr '_' ' ')"
	
	NEWINFILENAME="$(basename ${INFILE} .pdb)_rebuilt"
	
	if [ -n "$MUTATE_SIDECHAINS" ]
	then
		if [ "$MUTATE_SIDECHAINS" != "any any original" ]
		then
			NEWINFILENAME="${NEWINFILENAME}_mutated_$(echo ${MUTATE_SIDECHAINS} | sed 's/\s\+/_/g' | tr ',' '-' | tr ':' '-')"
		fi
	fi
	
	NEWINFILE="${TMPLDIR}/${NEWINFILENAME}.pdb"
	
	cat "$INFILE" | ${SCRIPTDIR}/tools/voronota-js-pdb-utensil-run-faspr --mutate "$MUTATE_SIDECHAINS" > "$NEWINFILE"
	
	if [ ! -s "$NEWINFILE" ]
	then
		echo >&2 "Error: failed to rebuild sidechains for input file '${INFILE}'"
		exit 1
	fi
	
	INFILE="$NEWINFILE"
fi

if [ -n "$RELAX_WITH_OPENMM" ]
then
	RELAX_WITH_OPENMM_PARAMS="$(echo ${RELAX_WITH_OPENMM} | tr ':' ' ')"
	
	if [ "$RELAX_WITH_OPENMM_PARAMS" == "basic" ]
	then
		RELAX_WITH_OPENMM_PARAMS="--conda-path ${CONDA_PATH} --conda-env openmm-env --max-iterations 100"
	fi
	
	NEWINFILENAME="$(basename ${INFILE} .pdb)_relaxed"
	
	NEWINFILE="${TMPLDIR}/${NEWINFILENAME}.pdb"
	
	${SCRIPTDIR}/tools/relax-with-openmm ${RELAX_WITH_OPENMM_PARAMS} --input "$INFILE" --output "$NEWINFILE" --trim-output
	
	if [ ! -s "$NEWINFILE" ]
	then
		echo >&2 "Error: failed to relax input file"
		exit 1
	fi
	
	INFILE="$NEWINFILE"
fi

################################################################################

OUTPUT_ATOMS_FILE="$(substitute_in_string "${OUTPUT_ATOMS_FILE}" "INPUTNAME" "${INFILE}")"
OUTPUT_PER_CONTACT="$(substitute_in_string "${OUTPUT_PER_CONTACT}" "INPUTNAME" "${INFILE}")"
OUTPUT_PER_RESIDUE="$(substitute_in_string "${OUTPUT_PER_RESIDUE}" "INPUTNAME" "${INFILE}")"
OUTPUT_TABLE_FILE="$(substitute_in_string "${OUTPUT_TABLE_FILE}" "INPUTNAME" "${INFILE}")"
OUTPUT_VSCRIPT="$(substitute_in_string "${OUTPUT_VSCRIPT}" "INPUTNAME" "${INFILE}")"
OUTPUT_PYMOL_VSCRIPT="$(substitute_in_string "${OUTPUT_PYMOL_VSCRIPT}" "INPUTNAME" "${INFILE}")"

if [ -n "$OUTPUT_ATOMS_FILE" ]
then
	mkdir -p "$(dirname ${OUTPUT_ATOMS_FILE})"
	cp "$INFILE" "$OUTPUT_ATOMS_FILE"
fi

${SCRIPTDIR}/tools/calculate_vcblocks_and_run_trained_mlp_classifier.bash \
  "${SCRIPTDIR}/tools/trained_nn_models/training_5870c524a74c0e90c4e5a6ea40aac7bb/mlp_epoch_232.pt" \
  "$INFILE" \
  "$SUBSELECT_CONTACTS" \
> "${TMPLDIR}/table"

if [ ! -s "${TMPLDIR}/table" ]
then
	echo >&2 "Error: failed to generate predictions"
	exit 1
fi

cd "$TMPLDIR"

R --vanilla << 'EOF' > /dev/null
df=read.table("table", header=TRUE, stringsAsFactors=FALSE);
total_area=sum(df$main_rr_contact__area);
df$area_expected_to_vanish=(df$main_rr_contact__area*(1-df$predicted_probability_to_persist));
df$area_expected_to_persist=(df$main_rr_contact__area*(0+df$predicted_probability_to_persist));
df$bounded_probabilities=df$predicted_probability_to_persist;
df$bounded_probabilities[which(df$predicted_probability_to_persist<0.005)]=0.005;
df$bounded_probabilities[which(df$predicted_probability_to_persist>0.995)]=0.995;
df$area_badness=(df$main_rr_contact__area*log(df$bounded_probabilities));
df$area_goodness=(df$main_rr_contact__area*log(1.0-df$bounded_probabilities));
df$area_pseudoenergy=(df$area_goodness-df$area_badness);
total_area=sum(df$main_rr_contact__area);
total_area_expected_to_vanish=sum(df$area_expected_to_vanish);
total_area_expected_to_persist=sum(df$area_expected_to_persist);
total_area_pseudoenergy=sum(df$area_pseudoenergy);
total_area_badness=sum(df$area_badness);
total_area_goodness=sum(df$area_goodness);
df$exposure_value=(df$main_rr_contact__boundary)/sqrt(df$main_rr_contact__area);
ordering_by_exposure_value=order(0-df$exposure_value);
ordered_exposure_values=df$exposure_value[ordering_by_exposure_value];
ordered_area_pseudoenergies=df$area_pseudoenergy[ordering_by_exposure_value];
ordered_areas=df$main_rr_contact__area[ordering_by_exposure_value];
N=length(ordered_exposure_values);
M=max(1, length(which(ordered_exposure_values>0)));
subtotal_area_pseudoenergies=rep(0, M);
subtotal_areas=rep(0, M);
for(i in 1:M)
{
	subtotal_area_pseudoenergies[i]=sum(ordered_area_pseudoenergies[i:N]);
	subtotal_areas[i]=sum(ordered_areas[i:N]);
}
best_core_index=order(subtotal_area_pseudoenergies)[1];
best_core_area_pseudoenergy=subtotal_area_pseudoenergies[best_core_index];
best_core_area=subtotal_areas[best_core_index];
result=data.frame(ID="IDVALUE", area_pseudoenergy=total_area_pseudoenergy, area_total=total_area, area_expected_to_persist=total_area_expected_to_persist, area_goodness_pseudoenergy=total_area_goodness, best_core_pseudoenergy=best_core_area_pseudoenergy, best_core_area=best_core_area);
write.table(result, file="summary", row.names=FALSE, col.names=TRUE, quote=FALSE, sep="\t");

df$area=df$main_rr_contact__area;
df$boundary=df$main_rr_contact__boundary;
sdf1=df[,c("area_pseudoenergy", "area", "area_expected_to_persist", "area_goodness", "boundary")];
sdf2=sdf1;
sdf1$chain=df$chain1;
sdf1$seqnum=df$seqnum1;
sdf1$resname=df$resname1;
sdf2$chain=df$chain2;
sdf2$seqnum=df$seqnum2;
sdf2$resname=df$resname2;
sdf=rbind(sdf1, sdf2);
sdf_summarized=aggregate(. ~ chain + seqnum + resname, data=sdf, FUN=sum);
sdf_summarized=sdf_summarized[order(sdf_summarized$area_pseudoenergy),];
write.table(sdf_summarized, file="table_per_residue", row.names=FALSE, col.names=TRUE, quote=FALSE, sep="\t");

sdf=df[,c("chain1", "seqnum1", "resname1", "chain2", "seqnum2", "resname2", "area_pseudoenergy", "area", "boundary", "predicted_probability_to_persist")]
sdf=sdf[order(sdf$area_pseudoenergy),];
write.table(sdf, file="table_per_contact", row.names=FALSE, col.names=TRUE, quote=FALSE, sep="\t");
EOF

cd - &> /dev/null

if [ ! -s "${TMPLDIR}/summary" ]
then
	echo >&2 "Error: failed to global summary"
	exit 1
fi

if [ -n "$OUTPUT_PER_CONTACT" ]
then
	mkdir -p "$(dirname ${OUTPUT_PER_CONTACT})"
	cat "${TMPLDIR}/table_per_contact" > "$OUTPUT_PER_CONTACT"
fi

if [ -n "$OUTPUT_PER_RESIDUE" ]
then
	mkdir -p "$(dirname ${OUTPUT_PER_RESIDUE})"
	cat "${TMPLDIR}/table_per_residue" > "$OUTPUT_PER_RESIDUE"
fi

if [ -n "$OUTPUT_VSCRIPT" ] || [ -n "$OUTPUT_PYMOL_VSCRIPT" ]
then
	{
		echo 'color-atoms -col yellow'
		echo 'construct-contacts-radically-fast -no-intra-residue -generate-graphics'
		RRSET="$(cat ${TMPLDIR}/table | tail -n +2 | awk '{print $2 " " $3 " " $5 " " $6 " " $10}' | tr '\n' ' ')"
		echo "set-adjunct-of-contacts -use (${SUBSELECT_CONTACTS}) -name persistence -value 0.0 -residue-residue-values ${RRSET}"
		echo "show-contacts ((${SUBSELECT_CONTACTS}) and ([-v persistence]))"
		echo 'spectrum-contacts -use [_visible] -adjunct persistence -scheme rwb -min-val 0.0 -max-val 1.0'
	} > "${TMPLDIR}/vscript.vs"
	
	if [ -n "$OUTPUT_VSCRIPT" ]
	then
		mkdir -p "$(dirname ${OUTPUT_VSCRIPT})"
		cat "${TMPLDIR}/vscript.vs" > "$OUTPUT_VSCRIPT"
	fi
	
	if [ -n "$OUTPUT_PYMOL_VSCRIPT" ]
	then
		PYMOL_NAME="$(basename ${OUTPUT_PYMOL_VSCRIPT} .py | tr '.' '_')"
		mkdir -p "$(dirname ${OUTPUT_PYMOL_VSCRIPT})"
		
		{
			echo "import ${INFILE}"
			cat "${TMPLDIR}/vscript.vs"
			echo "export-contacts-as-pymol-cgo -use [_visible] -name ${PYMOL_NAME} -file ${OUTPUT_PYMOL_VSCRIPT}"
		} > "${TMPLDIR}/vscript_to_pymol.vs"
		
		echo "voronota_source('-file', '${TMPLDIR}/vscript_to_pymol.vs');" \
		| ${SCRIPTDIR}/tools/voronota-js 
	fi
fi

cat "${TMPLDIR}/summary" \
| sed "s|IDVALUE|$(basename ${INFILE})|" \
| column -t \
| {
if [ -n "$OUTPUT_TABLE_FILE" ] && [ "$OUTPUT_TABLE_FILE" != "_stdout" ]
then
	mkdir -p "$(dirname ${OUTPUT_TABLE_FILE})"
	cat > "$OUTPUT_TABLE_FILE"
else
	cat
fi
}


