#!/bin/bash

function print_help_and_exit
{
cat >&2 << 'EOF'

'voromarmotte' predicts persistence of contact areas in a protein structure

Options:
    --input | -i              string  *  input file path or '_list' to read file paths from stdin
    --inference-engine        string     MLP inference engine to use, can be 'onnx-mlp-standalone' (default) or 'onnx' or 'pytorch'
    --rebuild-sidechains      string     flag to rebuild side-chains with FASPR, can be 'false' or 'true', default is 'false'
    --mutate-sidechains       string     triples of strings (chain resnum resname) to define mutations and rebuild with FASPR
    --relax-with-openmm       string     parameters (':'-separated tokens, or 'basic') to enable the OpenMM relaxation, default is ''
    --subselect-contacts      string     query to subselect inter-chain contacts, default is '[]'
    --output-atoms-file       string     output file path for the processed input atoms
    --output-per-contact      string     output file path for the table of per-contact scores, default is ''
    --output-per-residue      string     output file path for the table of per-residue summary scores, default is ''
    --output-table-file       string     output file path for the global scores, default is '_stdout'
    --output-vscript          string     output file path for the visualization script for Voronota-GL
    --output-pymol-vscript    string     output file path for the visualization script for PyMol
    --processors              number     maximum number of processors to run in parallel, default is 1
    --sbatch-parameters       string     sbatch parameters to process '_list' input using Slurm, default is '' for no Slurm
    --help | -h                          flag to display help message and exit

Standard output:
    space-separated table of global scores

Examples:

    ./voromarmotte  --input ./model.pdb > ./table.txt
    
    ./voromarmotte  --input ./model.pdb --subselect-contacts '[-inter-chain]' > ./table.txt
    
    ./voromarmotte  --input ./model.pdb --subselect-contacts '[-a1 [-chain A]]' --output-per-contact ./table_of_contacts.txt > ./table.txt
    
    find ./models/ -type f -name '*.pdb' | ./voromarmotte --input _list --subselect-contacts '[-inter-chain]' --processors 16 > ./table.txt

EOF
exit 1
}

function substitute_in_string
{
	SUBSTITUTE_TEMPLATE="$1"
	SUBSTITUTE_SOURCE="$2"
	SUBSTITUTE_DESTINATION="$3"
	SUBSTITUTE_DESTINATION="$(basename ${SUBSTITUTE_DESTINATION} .pdb)"
	SUBSTITUTE_DESTINATION="$(basename ${SUBSTITUTE_DESTINATION} .cif)"
	echo "$SUBSTITUTE_TEMPLATE" | sed "s|${SUBSTITUTE_SOURCE}|${SUBSTITUTE_DESTINATION}|"
}

################################################################################

export LANG=C
export LC_ALL=C

VOROMARMOTTE_ROOT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

ALLARGS=("$@")

INFILE=""
INFERENCE_ENGINE="onnx-mlp-standalone"
REBUILD_SIDECHAINS="false"
MUTATE_SIDECHAINS=""
RELAX_WITH_OPENMM=""
SUBSELECT_CONTACTS="[]"
OUTPUT_ATOMS_FILE=""
OUTPUT_PER_CONTACT=""
OUTPUT_PER_RESIDUE=""
OUTPUT_TABLE_FILE=""
OUTPUT_VSCRIPT=""
OUTPUT_PYMOL_VSCRIPT=""
MAX_PROCESSORS="1"
SBATCH_PARAMETERS=""
STDIN_FILE="_stream"
HELP_MODE="false"

while [[ $# > 0 ]]
do
	OPTION="$1"
	OPTARG="$2"
	shift
	case $OPTION in
	-i|--input)
		INFILE="$OPTARG"
		shift
		;;
	--inference-engine)
		INFERENCE_ENGINE="$OPTARG"
		shift
		;;
	--rebuild-sidechains)
		REBUILD_SIDECHAINS="$OPTARG"
		shift
		;;
	--mutate-sidechains)
		MUTATE_SIDECHAINS="$OPTARG"
		shift
		;;
	--relax-with-openmm)
		RELAX_WITH_OPENMM="$OPTARG"
		shift
		;;
	--subselect-contacts)
		SUBSELECT_CONTACTS="$OPTARG"
		shift
		;;
	--output-atoms-file)
		OUTPUT_ATOMS_FILE="$OPTARG"
		shift
		;;
	--output-per-contact)
		OUTPUT_PER_CONTACT="$OPTARG"
		shift
		;;
	--output-per-residue)
		OUTPUT_PER_RESIDUE="$OPTARG"
		shift
		;;
	--output-vscript)
		OUTPUT_VSCRIPT="$OPTARG"
		shift
		;;
	--output-pymol-vscript)
		OUTPUT_PYMOL_VSCRIPT="$OPTARG"
		shift
		;;
	--output-table-file)
		OUTPUT_TABLE_FILE="$OPTARG"
		shift
		;;
	--processors)
		MAX_PROCESSORS="$OPTARG"
		shift
		;;
	--sbatch-parameters)
		SBATCH_PARAMETERS="$OPTARG"
		shift
		;;
	--voromarmotte-root-dir)
		VOROMARMOTTE_ROOT_DIR="$OPTARG"
		shift
		;;
	--stdin-file)
		STDIN_FILE="$OPTARG"
		shift
		;;
	-h|--help)
		HELP_MODE="true"
		;;
	*)
		echo >&2 "Error: invalid command line option '$OPTION'"
		exit 1
		;;
	esac
done

if [ "$HELP_MODE" == "true" ]
then
	print_help_and_exit
fi

################################################################################

if [ ! -s "${VOROMARMOTTE_ROOT_DIR}/voromarmotte" ] || [ ! -s "${VOROMARMOTTE_ROOT_DIR}/tools/voronota-js" ]
then
	if [ -n "$SLURM_JOB_ID" ]
	then
		VOROMARMOTTE_ROOT_DIR="$(dirname -- "$(squeue -j ${SLURM_JOB_ID} -h -O Command)")"
	fi
fi

if [ ! -s "${VOROMARMOTTE_ROOT_DIR}/voromarmotte" ] || [ ! -s "${VOROMARMOTTE_ROOT_DIR}/tools/voronota-js" ]
then
	echo >&2 "Error: cannot detect the VoroMarmotte software root directory, provide it with the --voromarmotte-root-dir oprion"
	exit 1
fi

################################################################################

if [ -z "$INFILE" ]
then
	echo >&2 "Error: no input provided"
	exit 1
fi

if [ "$INFILE" != "_list" ] && [ ! -s "$INFILE" ]
then
	echo >&2 "Error: input file '$INFILE' does not exist"
	exit 1
fi

if [ "$STDIN_FILE" != "_stream" ] && [ ! -s "$STDIN_FILE" ]
then
	echo >&2 "Error: stdin replacement file '$STDIN_FILE' does not exist"
	exit 1
fi

################################################################################

if [ "$INFERENCE_ENGINE" != "onnx-mlp-standalone" ] && [ "$INFERENCE_ENGINE" != "onnx" ] && [ "$INFERENCE_ENGINE" != "pytorch" ]
then
	echo >&2 "Error: invalid value '${INFERENCE_ENGINE}' for the inference engine name, must be 'onnx-mlp-standalone' or 'onnx' or 'pytorch'"
	exit 1
fi

if [ "$REBUILD_SIDECHAINS" == "no" ]
then
	REBUILD_SIDECHAINS="false"
fi

if [ "$REBUILD_SIDECHAINS" != "false" ] && [ "$REBUILD_SIDECHAINS" != "true" ]
then
	echo >&2 "Error: invalid value '${REBUILD_SIDECHAINS}' for the side-chain rebuilding flag, must be 'false' or 'true'"
	exit 1
fi

if [ "$MUTATE_SIDECHAINS" == "no" ] || [ "$MUTATE_SIDECHAINS" == "false" ]
then
	MUTATE_SIDECHAINS=""
fi

if [ "$RELAX_WITH_OPENMM" == "no" ] || [ "$RELAX_WITH_OPENMM" == "false" ]
then
	RELAX_WITH_OPENMM=""
fi

################################################################################

if [ -z "$MAX_PROCESSORS" ] || [ "$MAX_PROCESSORS" -ne "$MAX_PROCESSORS" ] || [ "$MAX_PROCESSORS" -lt "1" ]
then
	echo >&2 "Error: invalid number of processors '$MAX_PROCESSORS', must be a positive number"
	exit 1
fi

if [ -n "$SBATCH_PARAMETERS" ]
then
	command -v sbatch &> /dev/null || { echo >&2 "Error: 'sbatch' executable not in binaries path"; exit 1; }
	command -v squeue &> /dev/null || { echo >&2 "Error: 'squeue' executable not in binaries path"; exit 1; }
fi

################################################################################

readonly TMPLDIR=$(mktemp -d)
trap "rm -r $TMPLDIR" EXIT

################################################################################

if [ "$INFILE" == "_list" ]
then
	{
		if [ "$STDIN_FILE" == "_stream" ]
		then
			cat
		else
			cat "$STDIN_FILE"
		fi
	} \
	| grep -E . | sort | uniq > "$TMPLDIR/input_list"
	
	if [ ! -s "$TMPLDIR/input_list" ]
	then
		echo >&2 "Error: no stdin data"
		exit 1
	fi
	
	NUM_OF_INPUTS="$(cat ${TMPLDIR}/input_list | wc -l)"
	
	mkdir -p "$TMPLDIR/children_tables"
	
	if [ "$MAX_PROCESSORS" -lt "2" ] || [ "$NUM_OF_INPUTS" == "1" ]
	then
		cat "$TMPLDIR/input_list" \
		| {
		if [ "$MUTATE_SIDECHAINS" == "_list" ]
		then
			cat \
			| sed 's/^\s*\(\S\+\)\s\+\(.*\)$/\1_FIRSTGAP_\2/' | tr ' ' '_' | tr '\t' '_' | sed 's/_FIRSTGAP_/ /' \
			| awk -v outdir="$TMPLDIR/children_tables" '{print "--input " $1 " --mutate-sidechains " $2 " --output-table-file " outdir "/" NR ".pdb"}'
		else
			awk -v outdir="$TMPLDIR/children_tables" '{print "--input " $1 " --output-table-file " outdir "/" NR ".pdb"}'
		fi
		} \
		| xargs -L 1 -P 1 "${VOROMARMOTTE_ROOT_DIR}/voromarmotte" "${ALLARGS[@]}" --processors 1 --sbatch-parameters '' --voromarmotte-root-dir "$VOROMARMOTTE_ROOT_DIR"
	else
		SIZE_OF_PORTION="$(echo "a=$NUM_OF_INPUTS; b=$MAX_PROCESSORS; if(a%b) a/b+1 else a/b" | bc)"
		
		if [ "$SIZE_OF_PORTION" -gt "19997" ]
		then
			SIZE_OF_PORTION="19997"
		fi
		
		mkdir -p "$TMPLDIR/portions"
		
		split -l "$SIZE_OF_PORTION" "$TMPLDIR/input_list" "$TMPLDIR/portions/portion_"
		
		find $TMPLDIR/portions/ -type f -not -empty \
		| awk -v outdir="$TMPLDIR/children_tables" '{print "--stdin-file " $1 " --output-table-file " outdir "/" NR ".txt"}' \
		| {
			if [ -z "$SBATCH_PARAMETERS" ]
			then
				xargs -L 1 -P "$MAX_PROCESSORS" "${VOROMARMOTTE_ROOT_DIR}/voromarmotte" "${ALLARGS[@]}" --processors 1 --sbatch-parameters '' --input _list --voromarmotte-root-dir "$VOROMARMOTTE_ROOT_DIR"
			else
				mkdir -p "${TMPLDIR}/slurm_logs"
				
				xargs -L 1 -P 1 sbatch -o "${TMPLDIR}/slurm_logs/slurmjob-%j.out" -e "${TMPLDIR}/slurm_logs/slurmjob-%j.err" $SBATCH_PARAMETERS "${VOROMARMOTTE_ROOT_DIR}/voromarmotte" "${ALLARGS[@]}" --processors 1 --sbatch-parameters '' --input _list --voromarmotte-root-dir "$VOROMARMOTTE_ROOT_DIR" \
				| grep -E '^Submitted batch job ' \
				| awk '{print $4}' \
				> "$TMPLDIR/slurm_job_ids"
				
				sleep 1
				REMAINING_SLURM_JOBS="$(squeue | grep -f "$TMPLDIR/slurm_job_ids" | wc -l)"
				while [ "$REMAINING_SLURM_JOBS" -gt "0" ]
				do
					sleep 1
					REMAINING_SLURM_JOBS="$(squeue | grep -f "$TMPLDIR/slurm_job_ids" | wc -l)"
				done
				
				find "$TMPLDIR/slurm_logs/" -type f -not -empty | xargs -L 1 cat >&2
			fi
		}
	fi
	
	find "$TMPLDIR/children_tables" -type f -not -empty \
	| sort \
	| xargs -L 1 cat \
	| awk '{if(NR==1 || $1!="ID") print $0}' \
	| ${VOROMARMOTTE_ROOT_DIR}/tools/voronota-js --no-setup-defaults "js:voronota_tournament_sort('-input-file _stdin -output-file _stdout -columns pseudoenergy -multipliers -1 -tolerances 0.0');" \
	| column -t \
	> "$TMPLDIR/full_output_table"
	
	if [ -n "$OUTPUT_TABLE_FILE" ] && [ "$OUTPUT_TABLE_FILE" != "_stdout" ]
	then
		mkdir -p "$(dirname "$OUTPUT_TABLE_FILE")"
		cat "$TMPLDIR/full_output_table" > "$OUTPUT_TABLE_FILE"
	else
		cat "$TMPLDIR/full_output_table"
	fi
	
	exit 0
fi

################################################################################

INFILE="$(perl -MCwd=realpath -e 'print realpath($ARGV[0])' "$INFILE")"

if [ ! -s "$INFILE" ]
then
	echo >&2 "Error: input file '$INFILE' does not exist"
	exit 1
fi

if [ -n "$MUTATE_SIDECHAINS" ]
then
	if [[ "$MUTATE_SIDECHAINS" == "stabilize-interface-"* ]] || [[ "$MUTATE_SIDECHAINS" == "destabilize-interface-"* ]]
	then
		read OPTIMIZATION_MODE MUTATE_CHAIN MAX_TRIES MAX_MUTATIONS <<< "$(echo ${MUTATE_SIDECHAINS} | tr '-' ' ' | tr '_' ' ' | tr '=' ' ' | tr ':' ' ' | awk '{print $1 " " $3 " " $4 " " $5}')"
		
		if [ -z "$MUTATE_CHAIN" ] || [ -z "$MAX_TRIES" ] || [ -z "$MAX_MUTATIONS" ]
		then
			echo >&2 "Error: invalid interface mutation mode specifier, it must contain chain name, number of samples, max number of mutations - e.g. 'stabilize-interface-A-1000-10'."
			exit 1
		fi
		
		"${VOROMARMOTTE_ROOT_DIR}/voromarmotte" "${ALLARGS[@]}" --mutate-sidechains "interface-${MUTATE_CHAIN}-every" --output-table-file _stdout \
		> "${TMPLDIR}/single_mutations_table"
		
		cat "${TMPLDIR}/single_mutations_table" \
		| ${VOROMARMOTTE_ROOT_DIR}/tools/suggest-mutations-to-change-binding-stability "$OPTIMIZATION_MODE" "$MAX_TRIES" "$MAX_MUTATIONS" \
		| grep -E '.' \
		> "${TMPLDIR}/suggested_multipoint_mutations"
		
		{
			cat "${TMPLDIR}/single_mutations_table"
			
			if [ -s "${TMPLDIR}/suggested_multipoint_mutations" ]
			then
				cat "${TMPLDIR}/suggested_multipoint_mutations" \
				| sed "s|^|${INFILE} |" \
				| "${VOROMARMOTTE_ROOT_DIR}/voromarmotte" "${ALLARGS[@]}" --input _list --mutate-sidechains _list --output-table-file _stdout \
				| tail -n +2
			fi
		} \
		| {
			if [ "$OPTIMIZATION_MODE" == "stabilize" ]
			then
				${VOROMARMOTTE_ROOT_DIR}/tools/voronota-js --no-setup-defaults "js:voronota_tournament_sort('-input-file _stdin -output-file _stdout -columns ic_area_pseudoenergy -multipliers -1 -tolerances 0.0');"
			else
				${VOROMARMOTTE_ROOT_DIR}/tools/voronota-js --no-setup-defaults "js:voronota_tournament_sort('-input-file _stdin -output-file _stdout -columns ic_area_pseudoenergy -multipliers 1 -tolerances 0.0');"
			fi
		} \
		| column -t \
		> "${TMPLDIR}/final_mutations_table_ordered"
		
		if [ -n "$OUTPUT_TABLE_FILE" ] && [ "$OUTPUT_TABLE_FILE" != "_stdout" ]
		then
			mkdir -p "$(dirname "$OUTPUT_TABLE_FILE")"
			cat "$TMPLDIR/final_mutations_table_ordered" > "$OUTPUT_TABLE_FILE"
		else
			cat "$TMPLDIR/final_mutations_table_ordered"
		fi
		
		exit 0
	fi
	
	if [[ "$MUTATE_SIDECHAINS" == "interface"* ]]
	then
		read MUTATE_CHAIN MUTATE_TO_RNAME <<< "$(echo ${MUTATE_SIDECHAINS} | tr '-' ' ' | tr '_' ' ' | tr '=' ' ' | tr ':' ' ' | awk '{print $2 " " $3}')"
		{
			${VOROMARMOTTE_ROOT_DIR}/tools/voronota-lt \
			  --input "$INFILE" \
			  --compute-only-inter-chain-contacts \
			  --print-contacts-residue-level \
			2> /dev/null
		} \
		| awk '{if($1=="cr"){print $2 " " $3 "\n" $5 " " $6}}' | tr '|' ' ' | sort | uniq \
		| awk -v chainsel=${MUTATE_CHAIN} '{if($1==chainsel){print $2 " " $3}}' \
		| while read -r LINERNUM LINERNAME
		do
			if [ "$MUTATE_TO_RNAME" == "every" ]
			then
				for IRNAME in ALA ARG ASN ASP CYS GLN GLU GLY HIS ILE LEU LYS MET PHE PRO SER THR TRP TYR VAL
				do
					if [ "$IRNAME" != "$LINERNAME" ]
					then
						echo "${INFILE} ${MUTATE_CHAIN} ${LINERNUM} ${IRNAME}"
					fi
				done
			else
				if [ "$MUTATE_TO_RNAME" != "$LINERNAME" ]
				then
					echo "${INFILE} ${MUTATE_CHAIN} ${LINERNUM} ${MUTATE_TO_RNAME}"
				fi
			fi
		done \
		> "$TMPLDIR/input_mutations_list"
		
		if [ ! -s "$TMPLDIR/input_mutations_list" ]
		then
			echo >&2 "Error: failed to generated interface mutation requests"
			exit 1
		fi
		
		{
			cat "$TMPLDIR/input_mutations_list"
			echo "${INFILE} any any original"
		} \
		| "${VOROMARMOTTE_ROOT_DIR}/voromarmotte" "${ALLARGS[@]}" --input _list --mutate-sidechains _list
		
		exit 0
	fi
	
	if [[ "$MUTATE_SIDECHAINS" == *"every"* ]]
	then
		${VOROMARMOTTE_ROOT_DIR}/tools/voronota-lt \
		  --input "$INFILE" \
		  --write-input-balls-to-file "$TMPLDIR/all_input_atomic_balls" \
		  --exit-before-calculations \
		2> /dev/null

		for IRNAME in ALA ARG ASN ASP CYS GLN GLU GLY HIS ILE LEU LYS MET PHE PRO SER THR TRP TYR VAL
		do
			echo "$(echo "${MUTATE_SIDECHAINS}" | sed "s/every/${IRNAME}/g")"
		done \
		| tr ' ' '_' \
		| sort | uniq \
		> "$TMPLDIR/mutations_list_all"
		
		cat "$TMPLDIR/all_input_atomic_balls" \
		| awk '{print $1 "_" $2}' \
		| tr '|' '_' \
		| sort | uniq \
		> "$TMPLDIR/mutations_list_forbidden"
		
		{
			cat "$TMPLDIR/mutations_list_all"
			cat "$TMPLDIR/mutations_list_forbidden"
			cat "$TMPLDIR/mutations_list_forbidden"
		} \
		| sort | uniq -c \
		| awk '{if($1==1){print $2}}' \
		| tr '_' ' ' \
		| sed "s|^|${INFILE} |" \
		> "$TMPLDIR/input_mutations_list"
		
		if [ ! -s "$TMPLDIR/input_mutations_list" ]
		then
			echo >&2 "Error: failed to generated mutation requests"
			exit 1
		fi
		
		{
			cat "$TMPLDIR/input_mutations_list"
			echo "${INFILE} any any original"
		} \
		| "${VOROMARMOTTE_ROOT_DIR}/voromarmotte" "${ALLARGS[@]}" --input _list --mutate-sidechains _list
		
		exit 0
	fi
fi

INPUTMODIFICATION="no"

if [ "$REBUILD_SIDECHAINS" == "true" ] || [ -n "$MUTATE_SIDECHAINS" ]
then
	MUTATE_SIDECHAINS="$(echo ${MUTATE_SIDECHAINS} | tr '_' ' ')"

	INPUTMODIFICATION="${INPUTMODIFICATION}_rebuilt"
	
	if [ -n "$MUTATE_SIDECHAINS" ]
	then
		if [ "$MUTATE_SIDECHAINS" != "any any original" ]
		then
			INPUTMODIFICATION="${INPUTMODIFICATION}_mutated_$(echo ${MUTATE_SIDECHAINS} | sed 's/\s\+/_/g' | tr ',' '-' | tr ':' '-')"
		fi
	fi
	
	cat "$INFILE" | ${VOROMARMOTTE_ROOT_DIR}/tools/voronota-js-pdb-utensil-run-faspr --mutate "$MUTATE_SIDECHAINS" > "${TMPLDIR}/rebuilt.pdb"
	
	if [ ! -s "${TMPLDIR}/rebuilt.pdb" ]
	then
		echo >&2 "Error: failed to rebuild sidechains for input file '${INFILE}'"
		exit 1
	fi
	
	INFILE="${TMPLDIR}/$(basename ${INFILE})"
	
	mv "${TMPLDIR}/rebuilt.pdb" "$INFILE"
fi

if [ -n "$RELAX_WITH_OPENMM" ]
then
	RELAX_WITH_OPENMM_PARAMS="$(echo ${RELAX_WITH_OPENMM} | tr ':' ' ')"
	
	if [ "$RELAX_WITH_OPENMM_PARAMS" == "basic" ]
	then
		RELAX_WITH_OPENMM_PARAMS="--max-iterations 100"
	fi
	
	INPUTMODIFICATION="${INPUTMODIFICATION}_relaxed"
	
	${VOROMARMOTTE_ROOT_DIR}/tools/relax-with-openmm ${RELAX_WITH_OPENMM_PARAMS} --input "$INFILE" --output "${TMPLDIR}/relaxed.pdb" --trim-output
	
	if [ ! -s "${TMPLDIR}/relaxed.pdb" ]
	then
		echo >&2 "Error: failed to relax input file"
		exit 1
	fi
	
	INFILE="${TMPLDIR}/$(basename ${INFILE})"
	
	mv "${TMPLDIR}/relaxed.pdb" "$INFILE"
fi

INPUTMODIFICATION="$(echo ${INPUTMODIFICATION} | sed 's/^no_//')"

################################################################################

OUTPUT_ATOMS_FILE="$(substitute_in_string "${OUTPUT_ATOMS_FILE}" "INPUTNAME" "${INFILE}")"
OUTPUT_ATOMS_FILE="$(substitute_in_string "${OUTPUT_ATOMS_FILE}" "MODIFIED" "${INPUTMODIFICATION}")"

OUTPUT_PER_CONTACT="$(substitute_in_string "${OUTPUT_PER_CONTACT}" "INPUTNAME" "${INFILE}")"
OUTPUT_PER_CONTACT="$(substitute_in_string "${OUTPUT_PER_CONTACT}" "MODIFIED" "${INPUTMODIFICATION}")"

OUTPUT_PER_RESIDUE="$(substitute_in_string "${OUTPUT_PER_RESIDUE}" "INPUTNAME" "${INFILE}")"
OUTPUT_PER_RESIDUE="$(substitute_in_string "${OUTPUT_PER_RESIDUE}" "MODIFIED" "${INPUTMODIFICATION}")"

OUTPUT_TABLE_FILE="$(substitute_in_string "${OUTPUT_TABLE_FILE}" "INPUTNAME" "${INFILE}")"
OUTPUT_TABLE_FILE="$(substitute_in_string "${OUTPUT_TABLE_FILE}" "MODIFIED" "${INPUTMODIFICATION}")"

OUTPUT_VSCRIPT="$(substitute_in_string "${OUTPUT_VSCRIPT}" "INPUTNAME" "${INFILE}")"
OUTPUT_VSCRIPT="$(substitute_in_string "${OUTPUT_VSCRIPT}" "MODIFIED" "${INPUTMODIFICATION}")"

OUTPUT_PYMOL_VSCRIPT="$(substitute_in_string "${OUTPUT_PYMOL_VSCRIPT}" "INPUTNAME" "${INFILE}")"
OUTPUT_PYMOL_VSCRIPT="$(substitute_in_string "${OUTPUT_PYMOL_VSCRIPT}" "MODIFIED" "${INPUTMODIFICATION}")"

if [ -n "$OUTPUT_ATOMS_FILE" ]
then
	mkdir -p "$(dirname ${OUTPUT_ATOMS_FILE})"
	cp "$INFILE" "$OUTPUT_ATOMS_FILE"
fi

${VOROMARMOTTE_ROOT_DIR}/tools/calculate_vcblocks_and_run_trained_mlp_classifier.bash \
  "$INFERENCE_ENGINE" \
  "${VOROMARMOTTE_ROOT_DIR}/tools/trained_nn_models/training_5870c524a74c0e90c4e5a6ea40aac7bb/mlp_epoch_232.pt" \
  "$INFILE" \
  "$SUBSELECT_CONTACTS" \
> "${TMPLDIR}/table"

if [ ! -s "${TMPLDIR}/table" ]
then
	echo >&2 "Error: failed to generate predictions"
	exit 1
fi

cd "$TMPLDIR"

${VOROMARMOTTE_ROOT_DIR}/tools/r-alternative "$(basename ${INFILE})" "$INPUTMODIFICATION"

cd - &> /dev/null

if [ ! -s "${TMPLDIR}/summary" ]
then
	echo >&2 "Error: failed to global summary"
	exit 1
fi

if [ -n "$OUTPUT_PER_CONTACT" ]
then
	mkdir -p "$(dirname ${OUTPUT_PER_CONTACT})"
	cat "${TMPLDIR}/table_per_contact" > "$OUTPUT_PER_CONTACT"
fi

if [ -n "$OUTPUT_PER_RESIDUE" ]
then
	mkdir -p "$(dirname ${OUTPUT_PER_RESIDUE})"
	cat "${TMPLDIR}/table_per_residue" > "$OUTPUT_PER_RESIDUE"
fi

if [ -n "$OUTPUT_VSCRIPT" ] || [ -n "$OUTPUT_PYMOL_VSCRIPT" ]
then
	{
		echo 'color-atoms -col yellow'
		echo 'construct-contacts-radically-fast -no-intra-residue -generate-graphics'
		RRSET="$(cat ${TMPLDIR}/table | tail -n +2 | awk '{print $2 " " $3 " " $5 " " $6 " " $10}' | tr '\n' ' ')"
		echo "set-adjunct-of-contacts -use (${SUBSELECT_CONTACTS}) -name persistence -value 0.0 -residue-residue-values ${RRSET}"
		echo "show-contacts ((${SUBSELECT_CONTACTS}) and ([-v persistence]))"
		echo 'spectrum-contacts -use [_visible] -adjunct persistence -scheme rwb -min-val 0.0 -max-val 1.0'
	} > "${TMPLDIR}/vscript.vs"
	
	if [ -n "$OUTPUT_VSCRIPT" ]
	then
		mkdir -p "$(dirname ${OUTPUT_VSCRIPT})"
		cat "${TMPLDIR}/vscript.vs" > "$OUTPUT_VSCRIPT"
	fi
	
	if [ -n "$OUTPUT_PYMOL_VSCRIPT" ]
	then
		PYMOL_NAME="$(basename ${OUTPUT_PYMOL_VSCRIPT} .py | tr '.' '_')"
		mkdir -p "$(dirname ${OUTPUT_PYMOL_VSCRIPT})"
		
		{
			echo "import ${INFILE}"
			cat "${TMPLDIR}/vscript.vs"
			echo "export-contacts-as-pymol-cgo -use [_visible] -name ${PYMOL_NAME} -file ${TMPLDIR}/pymol_draw.py"
			echo "export-contacts-as-pymol-cgo -use (([_visible]) and ([-inter-chain])) -name ${PYMOL_NAME}_ic -file ${TMPLDIR}/pymol_draw_ic.py"
		} > "${TMPLDIR}/vscript_to_pymol.vs"
		
		echo "voronota_source('-file', '${TMPLDIR}/vscript_to_pymol.vs');" \
		| ${VOROMARMOTTE_ROOT_DIR}/tools/voronota-js
		
		{
			cat "${TMPLDIR}/pymol_draw.py"
			if [ -s "${TMPLDIR}/pymol_draw_ic.py" ] && [ "$(cat ${TMPLDIR}/pymol_draw_ic.py | wc -l)" -lt "$(cat ${TMPLDIR}/pymol_draw.py | wc -l)" ]
			then
				cat "${TMPLDIR}/pymol_draw_ic.py"
			fi
		} \
		> "$OUTPUT_PYMOL_VSCRIPT"
	fi
fi

cat "${TMPLDIR}/summary" \
| column -t \
| {
if [ -n "$OUTPUT_TABLE_FILE" ] && [ "$OUTPUT_TABLE_FILE" != "_stdout" ]
then
	mkdir -p "$(dirname ${OUTPUT_TABLE_FILE})"
	cat > "$OUTPUT_TABLE_FILE"
else
	cat
fi
}


