#!/bin/bash

cd "$( cd -- "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

export LANG=C
export LC_ALL=C

MODE="$1"
N_TO_OUTPUT="$2"
MAX_MUTATIONS="$3"
LASTARG="$4"

if [ -z "$MODE" ] || [ -z "$N_TO_OUTPUT" ] || [ -z "$MAX_MUTATIONS" ] || [ -n "$LASTARG" ]
then
	echo >&2 "Error: invalid number of command-line arguments, must be exactly three - mode ('stabilize' or 'destabilize'), number of results to otputput, max number of simultaneous mutations."
	exit 1
fi

if [ "$MODE" != "stabilize" ] && [ "$MODE" != "destabilize" ]
then
	echo >&2 "Error: invalid value '${MODE}' for the mode, must be 'stabilize' or 'destabilize'"
	exit 1
fi

readonly TMPLDIR=$(mktemp -d)
trap "rm -r $TMPLDIR" EXIT

cd "$TMPLDIR"

cat > ./raw_input

if [ "$MODE" == "stabilize" ]
then
	cat ./raw_input | tail -n +2 | awk '{print $2 " " $3 " " $8}' > ./table_initial
elif [ "$MODE" == "destabilize" ]
then
	cat ./raw_input | tail -n +2 | awk '{print $2 " " (0-$3) " " (0-$8)}' > ./table_initial
fi

read BASE_SCORE_FULL BASE_SCORE_IC <<< "$(cat ./table_initial | awk '{if($1=="rebuilt"){print $2 " " $3}}')"

cat ./table_initial \
| awk -v bsf="$BASE_SCORE_FULL" -v bsic="$BASE_SCORE_IC" '{if($2<bsf && $3<bsic){print $1 " " ((bsf-$2)+2*(bsic-$3))}}' \
| sed 's/^rebuilt_mutated_//' \
| sort -n -k2,2 -r \
| tr '_' ' ' \
| awk '{print $1 "_" $2 " " $3 " " $4}' \
> ./table_m1

cd - &> /dev/null

cat "${TMPLDIR}/table_m1" \
| ./sample-multiple-mutations 42 1 "$MAX_MUTATIONS" "$N_TO_OUTPUT" \
| tr ' ' '_'

exit 0

